---
outputMode: active
scale: 1
background:
  red: 0.18
  green: 0.21
  blue: 0.25
  opacity: 0.93
widget:
  margin:
    margins:
      - 400
      - 400
      - 400
      - 400
    widget:
      verticalLayout:
        - horizontalLayout:
            - margin:
                margins:
                  - 0
                  - 88
                  - 0
                  - 32
                widget:
                  verticalLayout:
                    - date:
                        font: ~
                        font_size: 24.0
                    - clock:
                        font: ~
                        font_size: 48.0
            - verticalLayout:
                - margin:
                    margins:
                      - 0
                      - 0
                      - 0
                      - 8
                    widget:
                      battery:
                        font: ~
                        font_size: 16.0
                        length: 0
                - margin:
                    margins:
                      - 0
                      - 0
                      - 0
                      - 8
                    widget:
                      backlight:
                        device: amdgpu_bl0
                        font: ~
                        font_size: 16.0
                        length: 0
                - margin:
                    margins:
                      - 0
                      - 0
                      - 0
                      - 8
                    widget:
                      pulseAudio:
                        font: ~
                        font_size: 16.0
                        length: 0
        - calendar:
            font_primary: ~
            font_secondary: ~
            font_size: 10.0
            sections: 3
        - launcher:
            font: ~
            font_size: 14.0
            length: 0
            app_opener: ""
            term_opener: ""
            url_opener: ""
fonts:
  mono: JetBrainsMono Nerd Font
  sans: Inter
